---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "https://aemstagems4-connectivity.ramtrucks.com/us/en"
      includePaths:
        - "https://aemstagems4-connectivity.ramtrucks.com/us/en.*"
      excludePaths: []
      authentication:
        method: "form"
        parameters:
          loginPageUrl: "https://aemstagems4-connectivity.ramtrucks.com/us/en/login"
          loginRequestUrl: "https://aemstagems4-connectivity.ramtrucks.com/us/en/login"
          loginRequestBody: "username={%username%}&password={%password%}"
        verification:
          method: "response"
          loggedInRegex: "Logout"
          loggedOutRegex: "Login"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
      sessionManagement:
        method: "cookie"
        parameters: {}
      technology:
        exclude: []
      users:
        - name: "test_user"
          credentials:
            password: "fcaswfactory90@mailinator.com"
            username: "da1@Otto"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
  - parameters:
      scanOnlyInScope: true
      enableTags: false
    rules: []
    name: "passiveScan-config"
    type: "passiveScan-config"
  - parameters:
      context: "Default Context"
      user: "test_user"
      url: ""
      maxDuration: 0
      maxDepth: 0
      maxChildren: 0
    name: "spider"
    type: "spider"
  - parameters:
      context: "Default Context"
      user: "test_user"
      url: ""
      maxDuration: 60
      maxCrawlDepth: 10
      numberOfBrowsers: 1
      runOnlyIfModern: false
    name: "spiderAjax"
    type: "spiderAjax"
  - parameters: {}
    name: "passiveScan-wait"
    type: "passiveScan-wait"
  - parameters:
      context: "Default Context"
      user: "test_user"
      policy: ""
      maxRuleDurationInMins: 0
      maxScanDurationInMins: 0
    policyDefinition:
      defaultStrength: "medium"
      defaultThreshold: "medium"
      rules: []
    name: "activeScan"
    type: "activeScan"
  - parameters:
      template: "risk-confidence-html"
      reportDir: ""
      reportTitle: "ZAP Scanning Report"
      reportDescription: ""
    name: "report"
    type: "report"
